### ISSUE TITLE
DBDriver - Websphere, Oracle DB with datasource setup throws error 

### ISSUE THREAD

**Issue by archetana** [simplity/simplity#54]
DSRA9010E: 'setReadOnly' is not supported on the WebSphere java.sql.Connection implementation.
[4/14/17 10:51:08:829 IST] 000001ea SystemOut     O 
Callback object threw an exception while working with the driver
[4/14/17 10:51:08:829 IST] 000001ea SystemOut     O 
org.simplity.kernel.ApplicationError: DSRA9010E: 'setReadOnly' is not supported on the WebSphere java.sql.Connection implementation.
	at org.simplity.kernel.db.DbDriver.getConnection(DbDriver.java:561)
	at org.simplity.kernel.db.DbDriver.workWithDriver(DbDriver.java:468)
....

**Comment by archetana** [comment]
Fix applied in commit b4c8acb4a8e3e83d4581e435eccfb7a2e1329a8b
